select * from competition;
insert into competition (competitionID, name, date, location, championship) values (1, 'Target Triumph', '2024-05-25', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (2, 'Bullseye Bash', '2024-12-03', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (3, 'Target Triumph', '2024-10-09', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (4, 'Golden Arrow Challenge', '2024-12-03', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (5, 'Arrowhead Invitational', '2024-09-16', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (6, 'Quiver Cup', '2024-07-24', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (7, 'Golden Arrow Challenge', '2024-05-12', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (8, 'Golden Arrow Challenge', '2024-05-01', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (9, 'Golden Arrow Challenge', '2024-11-17', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (10, 'Quiver Cup', '2024-04-30', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (11, 'Arrowhead Invitational', '2024-06-25', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (12, 'Target Triumph', '2024-06-21', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (13, 'Arrowhead Invitational', '2024-09-14', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (14, 'Golden Arrow Challenge', '2024-12-23', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (15, 'Target Triumph', '2024-07-10', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (16, 'Bullseye Bash', '2024-07-23', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (17, 'Arrowhead Invitational', '2024-12-21', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (18, 'Quiver Cup', '2024-06-27', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (19, 'Quiver Cup', '2024-07-29', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (20, 'Quiver Cup', '2024-10-19', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (21, 'Golden Arrow Challenge', '2024-11-29', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (22, 'Quiver Cup', '2024-10-23', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (23, 'Golden Arrow Challenge', '2024-11-18', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (24, 'Arrowhead Invitational', '2024-11-11', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (25, 'Target Triumph', '2024-11-03', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (26, 'Target Triumph', '2024-07-28', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (27, 'Quiver Cup', '2024-07-11', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (28, 'Arrowhead Invitational', '2024-10-13', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (29, 'Target Triumph', '2024-11-25', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (30, 'Target Triumph', '2024-10-14', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (31, 'Arrowhead Invitational', '2024-08-08', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (32, 'Golden Arrow Challenge', '2024-05-15', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (33, 'Bullseye Bash', '2024-08-10', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (34, 'Bullseye Bash', '2024-06-19', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (35, 'Golden Arrow Challenge', '2024-09-03', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (36, 'Bullseye Bash', '2024-07-01', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (37, 'Target Triumph', '2024-10-05', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (38, 'Arrowhead Invitational', '2024-08-22', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (39, 'Golden Arrow Challenge', '2024-09-20', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (40, 'Golden Arrow Challenge', '2024-08-22', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (41, 'Arrowhead Invitational', '2024-08-25', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (42, 'Golden Arrow Challenge', '2024-12-01', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (43, 'Bullseye Bash', '2024-09-06', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (44, 'Golden Arrow Challenge', '2024-05-25', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (45, 'Golden Arrow Challenge', '2024-06-26', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (46, 'Quiver Cup', '2024-11-03', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (47, 'Bullseye Bash', '2024-09-08', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (48, 'Bullseye Bash', '2024-10-08', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (49, 'Target Triumph', '2024-08-21', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (50, 'Target Triumph', '2024-12-05', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (51, 'Bullseye Bash', '2024-08-29', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (52, 'Arrowhead Invitational', '2024-11-09', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (53, 'Arrowhead Invitational', '2024-10-27', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (54, 'Golden Arrow Challenge', '2024-09-21', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (55, 'Target Triumph', '2024-08-21', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (56, 'Bullseye Bash', '2024-09-25', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (57, 'Target Triumph', '2024-11-15', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (58, 'Target Triumph', '2024-11-15', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (59, 'Arrowhead Invitational', '2024-09-10', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (60, 'Golden Arrow Challenge', '2024-10-04', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (61, 'Quiver Cup', '2024-12-21', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (62, 'Arrowhead Invitational', '2024-07-03', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (63, 'Arrowhead Invitational', '2024-08-26', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (64, 'Target Triumph', '2024-05-10', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (65, 'Arrowhead Invitational', '2024-07-14', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (66, 'Golden Arrow Challenge', '2024-07-01', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (67, 'Golden Arrow Challenge', '2024-05-31', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (68, 'Bullseye Bash', '2024-11-20', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (69, 'Quiver Cup', '2024-09-14', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (70, 'Golden Arrow Challenge', '2024-12-24', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (71, 'Target Triumph', '2024-10-04', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (72, 'Arrowhead Invitational', '2024-06-11', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (73, 'Golden Arrow Challenge', '2024-08-21', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (74, 'Golden Arrow Challenge', '2024-07-18', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (75, 'Golden Arrow Challenge', '2024-12-24', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (76, 'Golden Arrow Challenge', '2024-10-26', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (77, 'Target Triumph', '2024-08-08', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (78, 'Golden Arrow Challenge', '2024-10-02', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (79, 'Bullseye Bash', '2024-06-23', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (80, 'Bullseye Bash', '2024-12-16', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (81, 'Arrowhead Invitational', '2024-11-03', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (82, 'Bullseye Bash', '2024-06-14', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (83, 'Golden Arrow Challenge', '2024-09-01', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (84, 'Bullseye Bash', '2024-05-24', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (85, 'Bullseye Bash', '2024-05-31', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (86, 'Arrowhead Invitational', '2024-12-29', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (87, 'Target Triumph', '2024-05-25', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (88, 'Arrowhead Invitational', '2024-11-30', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (89, 'Quiver Cup', '2024-09-24', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (90, 'Bullseye Bash', '2024-08-21', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (91, 'Target Triumph', '2024-05-17', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (92, 'Golden Arrow Challenge', '2024-11-01', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (93, 'Arrowhead Invitational', '2024-08-24', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (94, 'Target Triumph', '2024-12-22', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (95, 'Arrowhead Invitational', '2024-10-12', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (96, 'Arrowhead Invitational', '2024-06-28', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (97, 'Arrowhead Invitational', '2024-05-23', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (98, 'Quiver Cup', '2024-12-29', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (99, 'Arrowhead Invitational', '2024-05-03', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (100, 'Golden Arrow Challenge', '2024-08-21', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (101, 'Golden Arrow Challenge', '2024-11-25', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (102, 'Target Triumph', '2024-05-03', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (103, 'Arrowhead Invitational', '2024-06-21', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (104, 'Target Triumph', '2024-11-22', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (105, 'Bullseye Bash', '2024-08-29', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (106, 'Golden Arrow Challenge', '2024-09-17', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (107, 'Target Triumph', '2024-12-03', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (108, 'Arrowhead Invitational', '2024-06-28', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (109, 'Bullseye Bash', '2024-08-12', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (110, 'Bullseye Bash', '2024-11-21', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (111, 'Bullseye Bash', '2024-05-16', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (112, 'Quiver Cup', '2024-08-13', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (113, 'Golden Arrow Challenge', '2024-10-01', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (114, 'Golden Arrow Challenge', '2024-07-25', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (115, 'Golden Arrow Challenge', '2024-08-23', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (116, 'Bullseye Bash', '2024-12-21', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (117, 'Bullseye Bash', '2024-05-03', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (118, 'Golden Arrow Challenge', '2024-07-03', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (119, 'Golden Arrow Challenge', '2024-08-15', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (120, 'Quiver Cup', '2024-09-08', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (121, 'Target Triumph', '2024-06-09', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (122, 'Bullseye Bash', '2024-09-20', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (123, 'Target Triumph', '2024-09-18', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (124, 'Bullseye Bash', '2024-09-20', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (125, 'Bullseye Bash', '2024-10-10', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (126, 'Golden Arrow Challenge', '2024-11-09', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (127, 'Bullseye Bash', '2024-05-05', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (128, 'Target Triumph', '2024-11-23', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (129, 'Target Triumph', '2024-05-04', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (130, 'Bullseye Bash', '2024-05-03', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (131, 'Arrowhead Invitational', '2024-10-29', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (132, 'Target Triumph', '2024-10-24', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (133, 'Golden Arrow Challenge', '2024-09-28', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (134, 'Quiver Cup', '2024-11-21', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (135, 'Target Triumph', '2024-05-28', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (136, 'Target Triumph', '2024-10-05', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (137, 'Arrowhead Invitational', '2024-11-13', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (138, 'Golden Arrow Challenge', '2024-09-14', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (139, 'Target Triumph', '2024-06-07', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (140, 'Arrowhead Invitational', '2024-09-10', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (141, 'Quiver Cup', '2024-06-23', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (142, 'Quiver Cup', '2024-08-03', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (143, 'Bullseye Bash', '2024-12-25', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (144, 'Target Triumph', '2024-07-21', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (145, 'Quiver Cup', '2024-06-28', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (146, 'Arrowhead Invitational', '2024-12-06', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (147, 'Arrowhead Invitational', '2024-06-15', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (148, 'Target Triumph', '2024-12-21', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (149, 'Golden Arrow Challenge', '2024-08-11', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (150, 'Quiver Cup', '2024-12-14', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (151, 'Golden Arrow Challenge', '2024-06-03', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (152, 'Golden Arrow Challenge', '2024-12-19', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (153, 'Golden Arrow Challenge', '2024-08-01', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (154, 'Golden Arrow Challenge', '2024-05-06', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (155, 'Quiver Cup', '2024-07-06', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (156, 'Golden Arrow Challenge', '2024-09-20', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (157, 'Bullseye Bash', '2024-08-12', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (158, 'Target Triumph', '2024-08-06', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (159, 'Target Triumph', '2024-08-10', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (160, 'Golden Arrow Challenge', '2024-08-14', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (161, 'Arrowhead Invitational', '2024-09-16', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (162, 'Arrowhead Invitational', '2024-06-15', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (163, 'Target Triumph', '2024-05-19', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (164, 'Arrowhead Invitational', '2024-12-10', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (165, 'Golden Arrow Challenge', '2024-09-08', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (166, 'Arrowhead Invitational', '2024-12-11', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (167, 'Arrowhead Invitational', '2024-07-10', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (168, 'Arrowhead Invitational', '2024-09-09', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (169, 'Arrowhead Invitational', '2024-07-13', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (170, 'Quiver Cup', '2024-08-16', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (171, 'Bullseye Bash', '2024-10-23', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (172, 'Quiver Cup', '2024-12-24', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (173, 'Arrowhead Invitational', '2024-12-22', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (174, 'Target Triumph', '2024-12-25', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (175, 'Target Triumph', '2024-10-19', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (176, 'Target Triumph', '2024-07-08', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (177, 'Target Triumph', '2024-12-01', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (178, 'Golden Arrow Challenge', '2024-05-15', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (179, 'Golden Arrow Challenge', '2024-12-09', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (180, 'Bullseye Bash', '2024-12-19', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (181, 'Bullseye Bash', '2024-11-23', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (182, 'Golden Arrow Challenge', '2024-08-11', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (183, 'Target Triumph', '2024-08-29', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (184, 'Arrowhead Invitational', '2024-08-05', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (185, 'Arrowhead Invitational', '2024-05-06', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (186, 'Golden Arrow Challenge', '2024-05-08', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (187, 'Arrowhead Invitational', '2024-10-12', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (188, 'Bullseye Bash', '2024-08-26', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (189, 'Bullseye Bash', '2024-08-16', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (190, 'Quiver Cup', '2024-08-15', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (191, 'Golden Arrow Challenge', '2024-07-23', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (192, 'Target Triumph', '2024-11-21', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (193, 'Golden Arrow Challenge', '2024-09-16', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (194, 'Bullseye Bash', '2024-12-25', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (195, 'Golden Arrow Challenge', '2024-09-19', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (196, 'Arrowhead Invitational', '2024-10-14', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (197, 'Target Triumph', '2024-08-09', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (198, 'Target Triumph', '2024-09-22', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (199, 'Bullseye Bash', '2024-12-01', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (200, 'Golden Arrow Challenge', '2024-12-27', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (201, 'Bullseye Bash', '2024-06-25', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (202, 'Target Triumph', '2024-09-24', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (203, 'Bullseye Bash', '2024-10-27', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (204, 'Bullseye Bash', '2024-09-23', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (205, 'Bullseye Bash', '2024-12-24', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (206, 'Quiver Cup', '2024-11-16', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (207, 'Arrowhead Invitational', '2024-07-11', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (208, 'Target Triumph', '2024-06-12', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (209, 'Target Triumph', '2024-07-28', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (210, 'Bullseye Bash', '2024-06-15', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (211, 'Bullseye Bash', '2024-08-09', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (212, 'Quiver Cup', '2024-07-08', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (213, 'Bullseye Bash', '2024-12-26', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (214, 'Target Triumph', '2024-10-23', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (215, 'Bullseye Bash', '2024-11-26', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (216, 'Quiver Cup', '2024-09-23', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (217, 'Bullseye Bash', '2024-05-12', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (218, 'Quiver Cup', '2024-11-22', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (219, 'Golden Arrow Challenge', '2024-05-29', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (220, 'Bullseye Bash', '2024-12-24', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (221, 'Golden Arrow Challenge', '2024-10-28', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (222, 'Target Triumph', '2024-07-13', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (223, 'Target Triumph', '2024-10-01', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (224, 'Quiver Cup', '2024-12-10', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (225, 'Arrowhead Invitational', '2024-06-11', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (226, 'Golden Arrow Challenge', '2024-05-30', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (227, 'Arrowhead Invitational', '2024-07-13', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (228, 'Golden Arrow Challenge', '2024-10-03', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (229, 'Bullseye Bash', '2024-09-12', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (230, 'Golden Arrow Challenge', '2024-09-26', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (231, 'Bullseye Bash', '2024-06-12', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (232, 'Bullseye Bash', '2024-09-11', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (233, 'Arrowhead Invitational', '2024-09-28', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (234, 'Quiver Cup', '2024-06-25', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (235, 'Arrowhead Invitational', '2024-05-29', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (236, 'Arrowhead Invitational', '2024-07-26', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (237, 'Arrowhead Invitational', '2024-12-09', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (238, 'Bullseye Bash', '2024-12-14', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (239, 'Golden Arrow Challenge', '2024-10-04', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (240, 'Quiver Cup', '2024-08-03', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (241, 'Target Triumph', '2024-10-28', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (242, 'Arrowhead Invitational', '2024-06-22', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (243, 'Target Triumph', '2024-06-25', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (244, 'Quiver Cup', '2024-07-14', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (245, 'Arrowhead Invitational', '2024-07-23', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (246, 'Golden Arrow Challenge', '2024-04-30', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (247, 'Target Triumph', '2024-09-15', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (248, 'Golden Arrow Challenge', '2024-10-06', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (249, 'Quiver Cup', '2024-06-01', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (250, 'Arrowhead Invitational', '2024-11-09', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (251, 'Arrowhead Invitational', '2024-08-06', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (252, 'Golden Arrow Challenge', '2024-11-16', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (253, 'Quiver Cup', '2024-05-22', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (254, 'Bullseye Bash', '2024-11-03', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (255, 'Bullseye Bash', '2024-05-19', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (256, 'Arrowhead Invitational', '2024-06-30', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (257, 'Quiver Cup', '2024-06-30', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (258, 'Arrowhead Invitational', '2024-07-15', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (259, 'Arrowhead Invitational', '2024-08-18', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (260, 'Golden Arrow Challenge', '2024-10-16', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (261, 'Bullseye Bash', '2024-06-03', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (262, 'Bullseye Bash', '2024-12-15', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (263, 'Target Triumph', '2024-05-29', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (264, 'Bullseye Bash', '2024-06-24', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (265, 'Quiver Cup', '2024-06-08', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (266, 'Target Triumph', '2024-06-29', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (267, 'Bullseye Bash', '2024-09-22', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (268, 'Golden Arrow Challenge', '2024-04-30', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (269, 'Bullseye Bash', '2024-07-08', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (270, 'Quiver Cup', '2024-06-01', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (271, 'Bullseye Bash', '2024-08-14', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (272, 'Arrowhead Invitational', '2024-11-15', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (273, 'Arrowhead Invitational', '2024-09-27', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (274, 'Bullseye Bash', '2024-11-06', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (275, 'Golden Arrow Challenge', '2024-06-28', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (276, 'Quiver Cup', '2024-06-06', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (277, 'Quiver Cup', '2024-08-06', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (278, 'Golden Arrow Challenge', '2024-12-09', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (279, 'Arrowhead Invitational', '2024-11-10', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (280, 'Quiver Cup', '2024-06-17', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (281, 'Quiver Cup', '2024-05-07', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (282, 'Arrowhead Invitational', '2024-08-12', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (283, 'Bullseye Bash', '2024-05-06', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (284, 'Golden Arrow Challenge', '2024-12-28', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (285, 'Target Triumph', '2024-05-18', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (286, 'Quiver Cup', '2024-05-24', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (287, 'Target Triumph', '2024-05-31', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (288, 'Target Triumph', '2024-05-09', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (289, 'Golden Arrow Challenge', '2024-12-17', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (290, 'Bullseye Bash', '2024-08-01', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (291, 'Golden Arrow Challenge', '2024-11-22', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (292, 'Quiver Cup', '2024-06-09', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (293, 'Arrowhead Invitational', '2024-07-30', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (294, 'Bullseye Bash', '2024-11-22', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (295, 'Bullseye Bash', '2024-07-08', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (296, 'Target Triumph', '2024-05-07', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (297, 'Target Triumph', '2024-06-04', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (298, 'Quiver Cup', '2024-10-05', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (299, 'Arrowhead Invitational', '2024-07-17', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (300, 'Arrowhead Invitational', '2024-05-16', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (301, 'Quiver Cup', '2024-09-28', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (302, 'Arrowhead Invitational', '2024-12-04', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (303, 'Quiver Cup', '2024-05-25', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (304, 'Golden Arrow Challenge', '2024-09-30', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (305, 'Bullseye Bash', '2024-06-10', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (306, 'Target Triumph', '2024-07-23', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (307, 'Quiver Cup', '2024-06-02', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (308, 'Target Triumph', '2024-06-18', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (309, 'Target Triumph', '2024-11-10', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (310, 'Bullseye Bash', '2024-11-15', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (311, 'Target Triumph', '2024-10-09', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (312, 'Quiver Cup', '2024-12-15', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (313, 'Arrowhead Invitational', '2024-12-30', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (314, 'Quiver Cup', '2024-10-02', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (315, 'Bullseye Bash', '2024-07-06', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (316, 'Quiver Cup', '2024-09-02', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (317, 'Target Triumph', '2024-09-30', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (318, 'Golden Arrow Challenge', '2024-06-09', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (319, 'Quiver Cup', '2024-08-13', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (320, 'Golden Arrow Challenge', '2024-09-04', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (321, 'Bullseye Bash', '2024-08-24', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (322, 'Target Triumph', '2024-05-01', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (323, 'Target Triumph', '2024-07-27', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (324, 'Arrowhead Invitational', '2024-10-13', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (325, 'Bullseye Bash', '2024-09-09', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (326, 'Target Triumph', '2024-10-15', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (327, 'Quiver Cup', '2024-07-25', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (328, 'Quiver Cup', '2024-08-12', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (329, 'Arrowhead Invitational', '2024-06-28', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (330, 'Arrowhead Invitational', '2024-10-11', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (331, 'Quiver Cup', '2024-09-03', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (332, 'Target Triumph', '2024-10-09', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (333, 'Arrowhead Invitational', '2024-11-27', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (334, 'Bullseye Bash', '2024-10-22', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (335, 'Bullseye Bash', '2024-07-25', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (336, 'Bullseye Bash', '2024-12-13', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (337, 'Arrowhead Invitational', '2024-08-18', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (338, 'Arrowhead Invitational', '2024-10-12', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (339, 'Arrowhead Invitational', '2024-12-29', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (340, 'Golden Arrow Challenge', '2024-12-17', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (341, 'Target Triumph', '2024-11-04', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (342, 'Arrowhead Invitational', '2024-07-14', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (343, 'Target Triumph', '2024-07-10', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (344, 'Arrowhead Invitational', '2024-07-08', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (345, 'Quiver Cup', '2024-11-03', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (346, 'Quiver Cup', '2024-10-19', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (347, 'Quiver Cup', '2024-11-12', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (348, 'Target Triumph', '2024-08-22', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (349, 'Bullseye Bash', '2024-07-08', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (350, 'Arrowhead Invitational', '2024-09-12', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (351, 'Quiver Cup', '2024-08-25', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (352, 'Bullseye Bash', '2024-09-10', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (353, 'Bullseye Bash', '2024-09-14', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (354, 'Golden Arrow Challenge', '2024-06-02', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (355, 'Bullseye Bash', '2024-10-02', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (356, 'Target Triumph', '2024-12-11', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (357, 'Quiver Cup', '2024-10-01', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (358, 'Golden Arrow Challenge', '2024-11-14', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (359, 'Golden Arrow Challenge', '2024-09-13', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (360, 'Target Triumph', '2024-07-30', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (361, 'Target Triumph', '2024-07-12', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (362, 'Quiver Cup', '2024-08-03', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (363, 'Quiver Cup', '2024-09-25', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (364, 'Quiver Cup', '2024-05-06', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (365, 'Bullseye Bash', '2024-07-16', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (366, 'Bullseye Bash', '2024-07-13', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (367, 'Quiver Cup', '2024-06-06', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (368, 'Golden Arrow Challenge', '2024-06-27', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (369, 'Bullseye Bash', '2024-09-14', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (370, 'Arrowhead Invitational', '2024-08-16', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (371, 'Target Triumph', '2024-09-20', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (372, 'Arrowhead Invitational', '2024-12-24', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (373, 'Bullseye Bash', '2024-05-08', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (374, 'Quiver Cup', '2024-10-02', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (375, 'Bullseye Bash', '2024-08-07', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (376, 'Target Triumph', '2024-05-17', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (377, 'Bullseye Bash', '2024-06-08', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (378, 'Quiver Cup', '2024-06-05', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (379, 'Target Triumph', '2024-06-23', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (380, 'Target Triumph', '2024-06-20', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (381, 'Target Triumph', '2024-11-06', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (382, 'Bullseye Bash', '2024-07-28', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (383, 'Bullseye Bash', '2024-05-19', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (384, 'Arrowhead Invitational', '2024-07-07', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (385, 'Target Triumph', '2024-12-26', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (386, 'Arrowhead Invitational', '2024-10-23', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (387, 'Bullseye Bash', '2024-08-08', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (388, 'Target Triumph', '2024-08-30', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (389, 'Golden Arrow Challenge', '2024-10-02', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (390, 'Quiver Cup', '2024-07-01', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (391, 'Quiver Cup', '2024-11-05', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (392, 'Bullseye Bash', '2024-08-11', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (393, 'Arrowhead Invitational', '2024-06-13', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (394, 'Bullseye Bash', '2024-09-22', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (395, 'Target Triumph', '2024-12-23', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (396, 'Bullseye Bash', '2024-11-19', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (397, 'Target Triumph', '2024-04-30', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (398, 'Bullseye Bash', '2024-10-31', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (399, 'Target Triumph', '2024-10-10', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (400, 'Bullseye Bash', '2024-05-08', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (401, 'Golden Arrow Challenge', '2024-11-27', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (402, 'Bullseye Bash', '2024-12-19', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (403, 'Golden Arrow Challenge', '2024-07-29', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (404, 'Arrowhead Invitational', '2024-10-16', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (405, 'Target Triumph', '2024-05-31', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (406, 'Bullseye Bash', '2024-05-21', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (407, 'Target Triumph', '2024-10-06', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (408, 'Target Triumph', '2024-11-26', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (409, 'Target Triumph', '2024-12-12', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (410, 'Quiver Cup', '2024-12-29', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (411, 'Bullseye Bash', '2024-05-04', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (412, 'Golden Arrow Challenge', '2024-09-13', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (413, 'Quiver Cup', '2024-09-12', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (414, 'Bullseye Bash', '2024-07-23', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (415, 'Golden Arrow Challenge', '2024-05-03', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (416, 'Bullseye Bash', '2024-09-24', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (417, 'Arrowhead Invitational', '2024-08-10', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (418, 'Bullseye Bash', '2024-11-11', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (419, 'Quiver Cup', '2024-11-03', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (420, 'Golden Arrow Challenge', '2024-09-07', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (421, 'Quiver Cup', '2024-10-13', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (422, 'Golden Arrow Challenge', '2024-11-11', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (423, 'Bullseye Bash', '2024-08-19', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (424, 'Bullseye Bash', '2024-12-30', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (425, 'Target Triumph', '2024-10-11', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (426, 'Arrowhead Invitational', '2024-09-04', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (427, 'Bullseye Bash', '2024-09-10', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (428, 'Arrowhead Invitational', '2024-12-25', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (429, 'Bullseye Bash', '2024-08-18', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (430, 'Bullseye Bash', '2024-05-02', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (431, 'Bullseye Bash', '2024-09-03', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (432, 'Golden Arrow Challenge', '2024-11-30', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (433, 'Target Triumph', '2024-07-15', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (434, 'Target Triumph', '2024-08-12', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (435, 'Arrowhead Invitational', '2024-08-15', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (436, 'Golden Arrow Challenge', '2024-07-22', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (437, 'Target Triumph', '2024-05-02', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (438, 'Arrowhead Invitational', '2024-09-09', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (439, 'Bullseye Bash', '2024-11-07', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (440, 'Quiver Cup', '2024-12-07', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (441, 'Target Triumph', '2024-05-07', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (442, 'Target Triumph', '2024-11-15', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (443, 'Quiver Cup', '2024-08-03', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (444, 'Target Triumph', '2024-05-21', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (445, 'Quiver Cup', '2024-07-06', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (446, 'Bullseye Bash', '2024-11-12', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (447, 'Quiver Cup', '2024-08-13', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (448, 'Golden Arrow Challenge', '2024-08-10', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (449, 'Bullseye Bash', '2024-09-30', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (450, 'Target Triumph', '2024-09-09', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (451, 'Target Triumph', '2024-12-22', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (452, 'Golden Arrow Challenge', '2024-10-10', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (453, 'Quiver Cup', '2024-08-23', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (454, 'Golden Arrow Challenge', '2024-09-18', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (455, 'Arrowhead Invitational', '2024-08-02', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (456, 'Bullseye Bash', '2024-06-01', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (457, 'Quiver Cup', '2024-05-01', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (458, 'Golden Arrow Challenge', '2024-12-15', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (459, 'Quiver Cup', '2024-06-01', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (460, 'Quiver Cup', '2024-09-27', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (461, 'Arrowhead Invitational', '2024-06-13', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (462, 'Quiver Cup', '2024-12-28', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (463, 'Golden Arrow Challenge', '2024-04-30', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (464, 'Arrowhead Invitational', '2024-11-21', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (465, 'Bullseye Bash', '2024-05-17', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (466, 'Golden Arrow Challenge', '2024-07-10', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (467, 'Target Triumph', '2024-10-25', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (468, 'Target Triumph', '2024-08-27', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (469, 'Target Triumph', '2024-12-01', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (470, 'Target Triumph', '2024-06-30', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (471, 'Quiver Cup', '2024-11-02', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (472, 'Arrowhead Invitational', '2024-10-09', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (473, 'Bullseye Bash', '2024-11-22', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (474, 'Bullseye Bash', '2024-07-05', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (475, 'Quiver Cup', '2024-08-30', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (476, 'Target Triumph', '2024-12-06', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (477, 'Target Triumph', '2024-08-01', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (478, 'Bullseye Bash', '2024-05-19', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (479, 'Target Triumph', '2024-09-28', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (480, 'Quiver Cup', '2024-07-06', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (481, 'Bullseye Bash', '2024-05-23', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (482, 'Bullseye Bash', '2024-11-08', 'Sydney', true);
insert into competition (competitionID, name, date, location, championship) values (483, 'Golden Arrow Challenge', '2024-10-12', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (484, 'Target Triumph', '2024-07-13', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (485, 'Arrowhead Invitational', '2024-08-30', 'Adelaide', true);
insert into competition (competitionID, name, date, location, championship) values (486, 'Arrowhead Invitational', '2024-05-22', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (487, 'Golden Arrow Challenge', '2024-05-08', 'Sydney', false);
insert into competition (competitionID, name, date, location, championship) values (488, 'Bullseye Bash', '2024-12-04', 'Brisbane', false);
insert into competition (competitionID, name, date, location, championship) values (489, 'Bullseye Bash', '2024-06-21', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (490, 'Bullseye Bash', '2024-06-04', 'Perth', false);
insert into competition (competitionID, name, date, location, championship) values (491, 'Target Triumph', '2024-08-14', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (492, 'Golden Arrow Challenge', '2024-12-25', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (493, 'Bullseye Bash', '2024-07-03', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (494, 'Target Triumph', '2024-06-05', 'Melbourne', false);
insert into competition (competitionID, name, date, location, championship) values (495, 'Quiver Cup', '2024-09-08', 'Melbourne', true);
insert into competition (competitionID, name, date, location, championship) values (496, 'Target Triumph', '2024-11-17', 'Perth', true);
insert into competition (competitionID, name, date, location, championship) values (497, 'Bullseye Bash', '2024-11-06', 'Brisbane', true);
insert into competition (competitionID, name, date, location, championship) values (498, 'Arrowhead Invitational', '2024-05-16', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (499, 'Target Triumph', '2024-05-02', 'Adelaide', false);
insert into competition (competitionID, name, date, location, championship) values (500, 'Target Triumph', '2024-08-01', 'Adelaide', true);
-- SET SQL_SAFE_UPDATES = 0; 
-- delete from competition;
-- select * from competition where date = "2024-07-28";
-- create index idx_date on competition(date);