select * from recorder;
 SET SQL_SAFE_UPDATES = 0; 
-- recorder table
insert into recorder (recorderID, name) values (1, 'Tawnya Robillard');
insert into recorder (recorderID, name) values (2, 'Eran Bourthoumieux');
insert into recorder (recorderID, name) values (3, 'Pollyanna Kenner');
insert into recorder (recorderID, name) values (4, 'Mag Burdell');
insert into recorder (recorderID, name) values (5, 'Theo Hissett');
insert into recorder (recorderID, name) values (6, 'Rudd Whiffen');
insert into recorder (recorderID, name) values (7, 'Valentina Ledekker');
insert into recorder (recorderID, name) values (8, 'Paulina Borit');
insert into recorder (recorderID, name) values (9, 'Clarie Lailey');
insert into recorder (recorderID, name) values (10, 'Bendix Cufley');
insert into recorder (recorderID, name) values (11, 'Fair Tomkin');
insert into recorder (recorderID, name) values (12, 'Kristal Lasty');
insert into recorder (recorderID, name) values (13, 'Jessie Newrick');
insert into recorder (recorderID, name) values (14, 'Joell Cavil');
insert into recorder (recorderID, name) values (15, 'Enriqueta Farey');
insert into recorder (recorderID, name) values (16, 'Dick Bolens');
insert into recorder (recorderID, name) values (17, 'Konrad Briers');
insert into recorder (recorderID, name) values (18, 'Lillis Stroband');
insert into recorder (recorderID, name) values (19, 'Carroll Seyler');
insert into recorder (recorderID, name) values (20, 'Dalt Shilton');
insert into recorder (recorderID, name) values (21, 'Drud Caveau');
insert into recorder (recorderID, name) values (22, 'Renaud Boles');
insert into recorder (recorderID, name) values (23, 'Joly Whittall');
insert into recorder (recorderID, name) values (24, 'Oren Embling');
insert into recorder (recorderID, name) values (25, 'Lorne Bardwall');
insert into recorder (recorderID, name) values (26, 'Justina Garretts');
insert into recorder (recorderID, name) values (27, 'Letizia Ybarra');
insert into recorder (recorderID, name) values (28, 'Skylar Balls');
insert into recorder (recorderID, name) values (29, 'Margareta Rogister');
insert into recorder (recorderID, name) values (30, 'Gardiner Sedgebeer');
insert into recorder (recorderID, name) values (31, 'Gillian Issard');
insert into recorder (recorderID, name) values (32, 'Tildy Deekes');
insert into recorder (recorderID, name) values (33, 'Filmer Dallas');
insert into recorder (recorderID, name) values (34, 'Alix Mulvagh');
insert into recorder (recorderID, name) values (35, 'Martie Maunders');
insert into recorder (recorderID, name) values (36, 'Barbabas Gradly');
insert into recorder (recorderID, name) values (37, 'Coralyn Souness');
insert into recorder (recorderID, name) values (38, 'Erv Duck');
insert into recorder (recorderID, name) values (39, 'Carmel Allbon');
insert into recorder (recorderID, name) values (40, 'Joelly Louisot');
insert into recorder (recorderID, name) values (41, 'Nickey Erratt');
insert into recorder (recorderID, name) values (42, 'Keri Stonman');
insert into recorder (recorderID, name) values (43, 'Waylen Butterfill');
insert into recorder (recorderID, name) values (44, 'Andris Coucher');
insert into recorder (recorderID, name) values (45, 'Caleb Pavlata');
insert into recorder (recorderID, name) values (46, 'Lonnie Bras');
insert into recorder (recorderID, name) values (47, 'Barde Lowrance');
insert into recorder (recorderID, name) values (48, 'Belicia Choppin');
insert into recorder (recorderID, name) values (49, 'Swen Levett');
insert into recorder (recorderID, name) values (50, 'Mellicent Summers');
insert into recorder (recorderID, name) values (51, 'Felisha Gilluley');
insert into recorder (recorderID, name) values (52, 'Carmen Ebourne');
insert into recorder (recorderID, name) values (53, 'Free Passmore');
insert into recorder (recorderID, name) values (54, 'Hettie Flavelle');
insert into recorder (recorderID, name) values (55, 'Maybelle Towlson');
insert into recorder (recorderID, name) values (56, 'Devland Gallichiccio');
insert into recorder (recorderID, name) values (57, 'Jobie Lundy');
insert into recorder (recorderID, name) values (58, 'Sofie Barabich');
insert into recorder (recorderID, name) values (59, 'Torin Conaboy');
insert into recorder (recorderID, name) values (60, 'Miriam Scottesmoor');
insert into recorder (recorderID, name) values (61, 'Brennan Capineer');
insert into recorder (recorderID, name) values (62, 'Giovanni Holdworth');
insert into recorder (recorderID, name) values (63, 'Merry Bayliss');
insert into recorder (recorderID, name) values (64, 'Knox Moorerud');
insert into recorder (recorderID, name) values (65, 'Isak Lilford');
insert into recorder (recorderID, name) values (66, 'Bernard De la Barre');
insert into recorder (recorderID, name) values (67, 'Murdock Lerway');
insert into recorder (recorderID, name) values (68, 'Madelyn Quainton');
insert into recorder (recorderID, name) values (69, 'Nettle Bruniges');
insert into recorder (recorderID, name) values (70, 'Merrielle Bullon');
insert into recorder (recorderID, name) values (71, 'Cele de Juares');
insert into recorder (recorderID, name) values (72, 'Lauren Haggeth');
insert into recorder (recorderID, name) values (73, 'Elaina Bernardi');
insert into recorder (recorderID, name) values (74, 'Annis Mintoft');
insert into recorder (recorderID, name) values (75, 'Melonie Lidgley');
insert into recorder (recorderID, name) values (76, 'Jordanna Canby');
insert into recorder (recorderID, name) values (77, 'Sonny Duffitt');
insert into recorder (recorderID, name) values (78, 'Karlan Scimone');
insert into recorder (recorderID, name) values (79, 'Luther Blackhurst');
insert into recorder (recorderID, name) values (80, 'Alice Neasam');
insert into recorder (recorderID, name) values (81, 'Janelle Simmonite');
insert into recorder (recorderID, name) values (82, 'Kaia Crippen');
insert into recorder (recorderID, name) values (83, 'Dacie Larkcum');
insert into recorder (recorderID, name) values (84, 'Hayes Shyres');
insert into recorder (recorderID, name) values (85, 'Caty Coston');
insert into recorder (recorderID, name) values (86, 'Kelley Snawdon');
insert into recorder (recorderID, name) values (87, 'Curr Wolseley');
insert into recorder (recorderID, name) values (88, 'Goldina Baxstair');
insert into recorder (recorderID, name) values (89, 'Mylo Rosoman');
insert into recorder (recorderID, name) values (90, 'Karlis Gogie');
insert into recorder (recorderID, name) values (91, 'Emmerich Treweela');
insert into recorder (recorderID, name) values (92, 'Ingra Cuttle');
insert into recorder (recorderID, name) values (93, 'Griffy Dunthorne');
insert into recorder (recorderID, name) values (94, 'Rolf Boynton');
insert into recorder (recorderID, name) values (95, 'Barde Mettetal');
insert into recorder (recorderID, name) values (96, 'Maybelle Carlet');
insert into recorder (recorderID, name) values (97, 'Pru Allsepp');
insert into recorder (recorderID, name) values (98, 'Skipton Brand-Hardy');
insert into recorder (recorderID, name) values (99, 'Mohandas Hatje');
insert into recorder (recorderID, name) values (100, 'Kara Conor');
-- delete from recorder;


alter table recorder add password varchar(5);
UPDATE recorder
SET password = 'admin';
select * from recorder;
CREATE INDEX idx_name on recorder(name);
select * from recorder ;
-- where name = 'Carmen Ebourne';
